### PR TITLE
Added erase and "dot" functionality painter2.dart

### PR DESCRIPTION
**Pull request by fellow7000**
1. Once user just taps on screen without swiping, circle will be drawn

2. You can "erase" you pathes using "eraser"

Example have not been updated!

### CODE REVIEW

**Comment by ja2375** [comment]
The PR seems to work perfectly :)

**Review by ja2375 — CHANGES_REQUESTED** [review]
Just a small request: Could you please update the example project to add there the eraser? So people can see how you planned the eraser tool to be used.
Thanks a lot!

**Comment by fellow7000** [comment]
> Just a small request: Could you please update the example project to add there the eraser? So people can see how you planned the eraser tool to be used.
> Thanks a lot!

Hi! Just read you message. As I mentioned, I had another PR with export / import paths functionality. So I will update example and make the second PR soon.

Thanks

**Comment by ja2375** [comment]
> > Just a small request: Could you please update the example project to add there the eraser? So people can see how you planned the eraser tool to be used.
> > Thanks a lot!
> 
> Hi! Just read you message. As I mentioned, I had another PR with export / import paths functionality. So I will update example and make the second PR soon.
> 
> Thanks

Ah, Ok!

**Pull request merged**
